var $ = require('../utils/jquery-3.1.1.min.js');
var common = require('../utils/common.util2.js');
require('../utils/scrolling.js');
var template=require('../utils/template.js');
var Body = require('../tpls/data/dataBody.string');
var Main = require('../tpls/data/dataMain.string');
var templates = require('../tpls/data/templates.string');
// var bodyList = require('../tpls/list/listMoudle.string');
//var common = require('../utils/input.js');
$(function() {
    common.renderBody($('body'), Body);
    common.append($('.main'), Main);
    common.append($('body'), templates);
    $('.item').on('click', function(event) {
        var tar = $(this).next();
        tar.hasClass('on') ? tar.removeClass('on') : tar.addClass('on');
    });
    $('#main-list').on('click', '.lbs', function(event) {
        event.stopPropagation()
        event.preventDefault();
        var tar1 = $(this);
        if (tar1.hasClass('on')) {
            tar1.removeClass('on');
        } else {
            $('.lbs').removeClass('on');
            tar1.addClass('on');
        };
    });

    function initScroll() {
        $('#main-list').scrollingOff();
        $('#list').scrollingOff();
        $('#main-list').scrolling({ backgroundColor: '#0a3f5e', width: '0.06rem', borderRadius: '0.03rem' }, { backgroundColor: '#0396c2', borderRadius: '0.03rem' });
        $('#list').scrolling({ backgroundColor: '#0a3f5e', width: '0.06rem', borderRadius: '0.03rem' }, { backgroundColor: '#0396c2', borderRadius: '0.03rem' });
    }
    initScroll();
    //缩放窗口事件
    var resizeEvt = 'orientationchange' in window ? 'orientationchange' : 'resize';
    window.addEventListener(resizeEvt, initScroll, false);

    //加载列表
    $.ajax({
            //url: 'http://172.16.1.174:8080/datasource/v1.0/datasourceByParam',
            url: '/datasource/v1.0/datasourceByParam',
            type: 'POST',
            dataType: 'json',
            data: { "pageNum": "1", "pageSize": "5", "dataSourceName": "", "businessSysName": "", "dataSourceOwner": "" },
            success: function(data) {
                //console.log(data)
            },
            error: function(err) {
                //console.log(err)
                var data = {
                    "msg": "数据源查询成功！",
                    "code": "200",
                    "page": {
                        "pageNum": 1,
                        "pageSize": 5,
                        "pageTotal": 8,
                        "totalSize": 39,
                        "list": [{
                            "physical_address": "1",
                            "hardware_configuration": "cpu",
                            "data_source_retention_cycle": "1年",
                            "del_state": "F",
                            "description": "通过acars发送放行，航路信息给机组",
                            "history_data_size": 2365841,
                            "data_source_status": "disconnect",
                            "data_source_owner": "新疆空管",
                            "data_base_name": "mysql",
                            "data_source_growth_rate": 20,
                            "protocol": "tcp",
                            "password": "root",
                            "link_string": "com.mysql.jdbc.Driver",
                            "equipment_model": "sunfire－X4150",
                            "data_base_bit": "64位",
                            "character_set": "UTF-8",
                            "os_bit": "64位",
                            "id": 49,
                            "org_name": null,
                            "data_bast_developers": "数据公司（ADCC）",
                            "creator": "1",
                            "os": "XscreenSaver 4.18",
                            "create_time": 1487647222000,
                            "data_source_type": "db",
                            "deployment_address": 110000,
                            "ip_address": "127.0.0.1",
                            "version": "11G",
                            "port": "3306",
                            "data_base_type": "oracle",
                            "data_source_name": "数字放行系统（DCL）",
                            "data_source_short_name": "DCL",
                            "aprove_status": "normal",
                            "business_sys_name": "数字放行系统",
                            "vest_in_organization": 1,
                            "username": "root",
                            "data_base_version": "2.1"
                        }, {
                            "physical_address": "1",
                            "hardware_configuration": null,
                            "data_source_retention_cycle": "1年",
                            "del_state": "F",
                            "description": "acars、语音两种传输方式，miit气象报文，半小时更新一次，离场相关数据人工填写",
                            "history_data_size": 13355441,
                            "data_source_status": "disconnect",
                            "data_source_owner": "新疆空管",
                            "data_base_name": null,
                            "data_source_growth_rate": null,
                            "protocol": "tcp",
                            "password": null,
                            "link_string": null,
                            "equipment_model": "sunfire－X4150",
                            "data_base_bit": null,
                            "character_set": null,
                            "os_bit": "64位",
                            "id": 2,
                            "org_name": "塔台管制室,进近管制室",
                            "data_bast_developers": "数据公司（ADCC）",
                            "creator": "2",
                            "os": "XscreenSaver 4.18",
                            "create_time": 1487647202000,
                            "data_source_type": "db",
                            "deployment_address": null,
                            "ip_address": null,
                            "version": "11G",
                            "port": null,
                            "data_base_type": "oracle",
                            "data_source_name": "自动通播系统（D－ATIS）",
                            "data_source_short_name": "D－ATIS",
                            "aprove_status": "normal",
                            "business_sys_name": "自动通播系统",
                            "vest_in_organization": 2,
                            "username": null,
                            "data_base_version": null
                        }, {
                            "physical_address": "1",
                            "hardware_configuration": null,
                            "data_source_retention_cycle": "1年",
                            "del_state": "F",
                            "description": "acars、语音两种传输方式，miit气象报文，半小时更新一次，离场相关数据人工填写",
                            "history_data_size": 13355441,
                            "data_source_status": "disconnect",
                            "data_source_owner": "新疆空管",
                            "data_base_name": null,
                            "data_source_growth_rate": null,
                            "protocol": "tcp",
                            "password": null,
                            "link_string": null,
                            "equipment_model": "sunfire－X4150",
                            "data_base_bit": null,
                            "character_set": null,
                            "os_bit": "64位",
                            "id": 2,
                            "org_name": "塔台管制室,进近管制室",
                            "data_bast_developers": "数据公司（ADCC）",
                            "creator": "2",
                            "os": "XscreenSaver 4.18",
                            "create_time": 1487647202000,
                            "data_source_type": "db",
                            "deployment_address": null,
                            "ip_address": null,
                            "version": "11G",
                            "port": null,
                            "data_base_type": "oracle",
                            "data_source_name": "自动通播系统（D－ATIS）",
                            "data_source_short_name": "D－ATIS",
                            "aprove_status": "normal",
                            "business_sys_name": "自动通播系统",
                            "vest_in_organization": 2,
                            "username": null,
                            "data_base_version": null
                        }, {
                            "physical_address": "1",
                            "hardware_configuration": null,
                            "data_source_retention_cycle": "1年",
                            "del_state": "F",
                            "description": "acars、语音两种传输方式，miit气象报文，半小时更新一次，离场相关数据人工填写",
                            "history_data_size": 13355441,
                            "data_source_status": "disconnect",
                            "data_source_owner": "新疆空管",
                            "data_base_name": null,
                            "data_source_growth_rate": null,
                            "protocol": "tcp",
                            "password": null,
                            "link_string": null,
                            "equipment_model": "sunfire－X4150",
                            "data_base_bit": null,
                            "character_set": null,
                            "os_bit": "64位",
                            "id": 2,
                            "org_name": "塔台管制室,进近管制室",
                            "data_bast_developers": "数据公司（ADCC）",
                            "creator": "2",
                            "os": "XscreenSaver 4.18",
                            "create_time": 1487647202000,
                            "data_source_type": "db",
                            "deployment_address": null,
                            "ip_address": null,
                            "version": "11G",
                            "port": null,
                            "data_base_type": "oracle",
                            "data_source_name": "自动通播系统（D－ATIS）",
                            "data_source_short_name": "D－ATIS",
                            "aprove_status": "normal",
                            "business_sys_name": "自动通播系统",
                            "vest_in_organization": 2,
                            "username": null,
                            "data_base_version": null
                        }, {
                            "physical_address": "1",
                            "hardware_configuration": null,
                            "data_source_retention_cycle": "1年",
                            "del_state": "F",
                            "description": "acars、语音两种传输方式，miit气象报文，半小时更新一次，离场相关数据人工填写",
                            "history_data_size": 13355441,
                            "data_source_status": "disconnect",
                            "data_source_owner": "新疆空管",
                            "data_base_name": null,
                            "data_source_growth_rate": null,
                            "protocol": "tcp",
                            "password": null,
                            "link_string": null,
                            "equipment_model": "sunfire－X4150",
                            "data_base_bit": null,
                            "character_set": null,
                            "os_bit": "64位",
                            "id": 2,
                            "org_name": "塔台管制室,进近管制室",
                            "data_bast_developers": "数据公司（ADCC）",
                            "creator": "2",
                            "os": "XscreenSaver 4.18",
                            "create_time": 1487647202000,
                            "data_source_type": "db",
                            "deployment_address": null,
                            "ip_address": null,
                            "version": "11G",
                            "port": null,
                            "data_base_type": "oracle",
                            "data_source_name": "自动通播系统（D－ATIS）",
                            "data_source_short_name": "D－ATIS",
                            "aprove_status": "normal",
                            "business_sys_name": "自动通播系统",
                            "vest_in_organization": 2,
                            "username": null,
                            "data_base_version": null
                        }, {
                            "physical_address": "1",
                            "hardware_configuration": null,
                            "data_source_retention_cycle": "1年",
                            "del_state": "F",
                            "description": "acars、语音两种传输方式，miit气象报文，半小时更新一次，离场相关数据人工填写",
                            "history_data_size": 13355441,
                            "data_source_status": "disconnect",
                            "data_source_owner": "新疆空管",
                            "data_base_name": null,
                            "data_source_growth_rate": null,
                            "protocol": "tcp",
                            "password": null,
                            "link_string": null,
                            "equipment_model": "sunfire－X4150",
                            "data_base_bit": null,
                            "character_set": null,
                            "os_bit": "64位",
                            "id": 2,
                            "org_name": "塔台管制室,进近管制室",
                            "data_bast_developers": "数据公司（ADCC）",
                            "creator": "2",
                            "os": "XscreenSaver 4.18",
                            "create_time": 1487647202000,
                            "data_source_type": "db",
                            "deployment_address": null,
                            "ip_address": null,
                            "version": "11G",
                            "port": null,
                            "data_base_type": "oracle",
                            "data_source_name": "自动通播系统（D－ATIS）",
                            "data_source_short_name": "D－ATIS",
                            "aprove_status": "normal",
                            "business_sys_name": "自动通播系统",
                            "vest_in_organization": 2,
                            "username": null,
                            "data_base_version": null
                        }, {
                            "physical_address": "1",
                            "hardware_configuration": null,
                            "data_source_retention_cycle": "1年",
                            "del_state": "F",
                            "description": "acars、语音两种传输方式，miit气象报文，半小时更新一次，离场相关数据人工填写",
                            "history_data_size": 13355441,
                            "data_source_status": "disconnect",
                            "data_source_owner": "新疆空管",
                            "data_base_name": null,
                            "data_source_growth_rate": null,
                            "protocol": "tcp",
                            "password": null,
                            "link_string": null,
                            "equipment_model": "sunfire－X4150",
                            "data_base_bit": null,
                            "character_set": null,
                            "os_bit": "64位",
                            "id": 2,
                            "org_name": "塔台管制室,进近管制室",
                            "data_bast_developers": "数据公司（ADCC）",
                            "creator": "2",
                            "os": "XscreenSaver 4.18",
                            "create_time": 1487647202000,
                            "data_source_type": "db",
                            "deployment_address": null,
                            "ip_address": null,
                            "version": "11G",
                            "port": null,
                            "data_base_type": "oracle",
                            "data_source_name": "自动通播系统（D－ATIS）",
                            "data_source_short_name": "D－ATIS",
                            "aprove_status": "normal",
                            "business_sys_name": "自动通播系统",
                            "vest_in_organization": 2,
                            "username": null,
                            "data_base_version": null
                        }, {
                            "physical_address": "1",
                            "hardware_configuration": null,
                            "data_source_retention_cycle": "1年",
                            "del_state": "F",
                            "description": "acars、语音两种传输方式，miit气象报文，半小时更新一次，离场相关数据人工填写",
                            "history_data_size": 13355441,
                            "data_source_status": "disconnect",
                            "data_source_owner": "新疆空管",
                            "data_base_name": null,
                            "data_source_growth_rate": null,
                            "protocol": "tcp",
                            "password": null,
                            "link_string": null,
                            "equipment_model": "sunfire－X4150",
                            "data_base_bit": null,
                            "character_set": null,
                            "os_bit": "64位",
                            "id": 2,
                            "org_name": "塔台管制室,进近管制室",
                            "data_bast_developers": "数据公司（ADCC）",
                            "creator": "2",
                            "os": "XscreenSaver 4.18",
                            "create_time": 1487647202000,
                            "data_source_type": "db",
                            "deployment_address": null,
                            "ip_address": null,
                            "version": "11G",
                            "port": null,
                            "data_base_type": "oracle",
                            "data_source_name": "自动通播系统（D－ATIS）",
                            "data_source_short_name": "D－ATIS",
                            "aprove_status": "normal",
                            "business_sys_name": "自动通播系统",
                            "vest_in_organization": 2,
                            "username": null,
                            "data_base_version": null
                        }, {
                            "physical_address": "1",
                            "hardware_configuration": null,
                            "data_source_retention_cycle": "1年",
                            "del_state": "F",
                            "description": "acars、语音两种传输方式，miit气象报文，半小时更新一次，离场相关数据人工填写",
                            "history_data_size": 13355441,
                            "data_source_status": "disconnect",
                            "data_source_owner": "新疆空管",
                            "data_base_name": null,
                            "data_source_growth_rate": null,
                            "protocol": "tcp",
                            "password": null,
                            "link_string": null,
                            "equipment_model": "sunfire－X4150",
                            "data_base_bit": null,
                            "character_set": null,
                            "os_bit": "64位",
                            "id": 2,
                            "org_name": "塔台管制室,进近管制室",
                            "data_bast_developers": "数据公司（ADCC）",
                            "creator": "2",
                            "os": "XscreenSaver 4.18",
                            "create_time": 1487647202000,
                            "data_source_type": "db",
                            "deployment_address": null,
                            "ip_address": null,
                            "version": "11G",
                            "port": null,
                            "data_base_type": "oracle",
                            "data_source_name": "自动通播系统（D－ATIS）",
                            "data_source_short_name": "D－ATIS",
                            "aprove_status": "normal",
                            "business_sys_name": "自动通播系统",
                            "vest_in_organization": 2,
                            "username": null,
                            "data_base_version": null
                        }, {
                            "physical_address": "1",
                            "hardware_configuration": null,
                            "data_source_retention_cycle": "1年",
                            "del_state": "F",
                            "description": "acars、语音两种传输方式，miit气象报文，半小时更新一次，离场相关数据人工填写",
                            "history_data_size": 13355441,
                            "data_source_status": "disconnect",
                            "data_source_owner": "新疆空管",
                            "data_base_name": null,
                            "data_source_growth_rate": null,
                            "protocol": "tcp",
                            "password": null,
                            "link_string": null,
                            "equipment_model": "sunfire－X4150",
                            "data_base_bit": null,
                            "character_set": null,
                            "os_bit": "64位",
                            "id": 2,
                            "org_name": "塔台管制室,进近管制室",
                            "data_bast_developers": "数据公司（ADCC）",
                            "creator": "2",
                            "os": "XscreenSaver 4.18",
                            "create_time": 1487647202000,
                            "data_source_type": "db",
                            "deployment_address": null,
                            "ip_address": null,
                            "version": "11G",
                            "port": null,
                            "data_base_type": "oracle",
                            "data_source_name": "自动通播系统（D－ATIS）",
                            "data_source_short_name": "D－ATIS",
                            "aprove_status": "normal",
                            "business_sys_name": "自动通播系统",
                            "vest_in_organization": 2,
                            "username": null,
                            "data_base_version": null
                        }, {
                            "physical_address": "1",
                            "hardware_configuration": null,
                            "data_source_retention_cycle": "1年",
                            "del_state": "F",
                            "description": "显示流控信息、军方活动、道面信息、炮射、天气信息、航情通告等信息",
                            "history_data_size": 41441211,
                            "data_source_status": "disconnect",
                            "data_source_owner": "新疆空管",
                            "data_base_name": null,
                            "data_source_growth_rate": null,
                            "protocol": "tcp",
                            "password": null,
                            "link_string": null,
                            "equipment_model": "IBM x3650 m4",
                            "data_base_bit": null,
                            "character_set": null,
                            "os_bit": "64位",
                            "id": 3,
                            "org_name": "塔台管制室,进近管制室,区域管制室,流量室",
                            "data_bast_developers": "数据公司（ADCC）",
                            "creator": "3",
                            "os": "Redhat 5.8 x64",
                            "create_time": 1487647202000,
                            "data_source_type": "db",
                            "deployment_address": null,
                            "ip_address": null,
                            "version": "5.7.17",
                            "port": null,
                            "data_base_type": "oracle",
                            "data_source_name": "综合显示系统（SIPDS）",
                            "data_source_short_name": "SIPDS",
                            "aprove_status": "normal",
                            "business_sys_name": "综合显示系统",
                            "vest_in_organization": 3,
                            "username": null,
                            "data_base_version": null
                        }, {
                            "physical_address": "1",
                            "hardware_configuration": null,
                            "data_source_retention_cycle": "1年",
                            "del_state": "F",
                            "description": "备份通话语音",
                            "history_data_size": 12354837,
                            "data_source_status": "disconnect",
                            "data_source_owner": "新疆空管",
                            "data_base_name": null,
                            "data_source_growth_rate": null,
                            "protocol": "tcp",
                            "password": null,
                            "link_string": null,
                            "equipment_model": "sunfire－X4150",
                            "data_base_bit": null,
                            "character_set": null,
                            "os_bit": "64位",
                            "id": 4,
                            "org_name": "塔台管制室,进近管制室",
                            "data_bast_developers": "芬兰维萨拉",
                            "creator": "4",
                            "os": "XscreenSaver 4.18",
                            "create_time": 1487647202000,
                            "data_source_type": "db",
                            "deployment_address": null,
                            "ip_address": null,
                            "version": "10G",
                            "port": null,
                            "data_base_type": "oracle",
                            "data_source_name": "语音记录仪",
                            "data_source_short_name": "语音记录仪",
                            "aprove_status": "normal",
                            "business_sys_name": "语音记录仪",
                            "vest_in_organization": 2,
                            "username": null,
                            "data_base_version": null
                        }, {
                            "physical_address": "1",
                            "hardware_configuration": null,
                            "data_source_retention_cycle": "1年",
                            "del_state": "F",
                            "description": "显示能见度、跑道视距（RVR）、风速风向、修正海压等信息",
                            "history_data_size": 54587511,
                            "data_source_status": "disconnect",
                            "data_source_owner": "新疆空管",
                            "data_base_name": null,
                            "data_source_growth_rate": null,
                            "protocol": "tcp",
                            "password": null,
                            "link_string": null,
                            "equipment_model": "sunfire－X4150",
                            "data_base_bit": null,
                            "character_set": null,
                            "os_bit": "64位",
                            "id": 5,
                            "org_name": "塔台管制室,进近管制室,区域管制室,气象中心观测室",
                            "data_bast_developers": "芬兰维萨拉",
                            "creator": "5",
                            "os": "XscreenSaver 4.18",
                            "create_time": 1487647202000,
                            "data_source_type": "db",
                            "deployment_address": null,
                            "ip_address": null,
                            "version": "10G",
                            "port": null,
                            "data_base_type": "oracle",
                            "data_source_name": "气象自动观测系统（AWOS）",
                            "data_source_short_name": "AWOS",
                            "aprove_status": "normal",
                            "business_sys_name": "气象自动观测系统",
                            "vest_in_organization": 1,
                            "username": null,
                            "data_base_version": null
                        }]
                    }
                }

                if (data.code == "200") {
                    var list = data.page.list;
                    for (var i = 0; i < list.length; i++) {

                        list[i].data_source_name = list[i].data_source_name ? list[i].data_source_name : '';
                        list[i].data_source_type = list[i].data_source_type ? list[i].data_source_type : '';
                        list[i].deployment_address = list[i].deployment_address ? list[i].deployment_address : '';
                        list[i].create_time = formatTime(list[i].create_time);
                        list[i].data_source_owner = list[i].data_source_owner ? list[i].data_source_owner : '';
                        list[i].data_source_status == 'disconnect' ? list[i].data_source_status = 'reject' : list[i].data_source_status = 'connect';
                    }

                    var  html  =  template('tpl-data', data.page);
                    $('#main-list').html(html);
                }
            }

        })
        .always(function() {
            initScroll();
        });

    //格式化时间
    function formatTime(num) {
        var date = new Date;
        date.setTime(num)
        var y = date.getFullYear();
        var m = date.getMonth() + 1;
        var d = date.getDate();
        m = m < 10 ? ("0" + m) : m;
        d = d < 10 ? ("0" + d) : d;
        return y + '-' + m + '-' + d;
    }
})
